# .yarnrc.yml
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.5.1.cjs

npmScopes:
  saas-ui-pro:
    npmRegistryServer: "https://npm.saas-ui.dev"

npmRegistries:
  //npm.saas-ui.dev:
    npmAuthIdent: "francescopelosio-debug:98A245AC-4A49-494A-B6D8-002386423422"
    npmAlwaysAuth: true
