// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from 'react'

export const Index: Record<string, any> = {
  default: {
    'task-card-with-properties': {
      name: 'task-card-with-properties',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/cards/task-card-with-properties/task-card-with-properties.tsx',
        '../blocks/cards/task-card-with-properties/task-card-with-properties.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/cards/task-card-with-properties/task-card-with-properties.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/cards/task-card-with-properties/task-card-with-properties.tsx',
      category: 'Application',
      subcategory: 'Cards',
      chunks: [],
    },
    'chat-details': {
      name: 'chat-details',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/communication/chat-details/chat-details.tsx',
        '../blocks/communication/chat-details/chat-details.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/communication/chat-details/chat-details.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/communication/chat-details/chat-details.tsx',
      category: 'Application',
      subcategory: 'Communication',
      chunks: [],
    },
    'latest-messages-card': {
      name: 'latest-messages-card',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/communication/latest-messages-card/latest-messages-card.tsx',
        '../blocks/communication/latest-messages-card/latest-messages-card.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/communication/latest-messages-card/latest-messages-card.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/communication/latest-messages-card/latest-messages-card.tsx',
      category: 'Application',
      subcategory: 'Communication',
      chunks: [],
    },
    'add-contact-drawer': {
      name: 'add-contact-drawer',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/drawers/add-contact-drawer/add-contact-drawer.tsx',
        '../blocks/drawers/add-contact-drawer/add-contact-drawer.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/drawers/add-contact-drawer/add-contact-drawer.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/drawers/add-contact-drawer/add-contact-drawer.tsx',
      category: 'Application',
      subcategory: 'Drawers',
      chunks: [],
    },
    'file-cards': {
      name: 'file-cards',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/drawers/add-contact-drawer/add-contact-drawer.tsx',
        '../blocks/drawers/add-contact-drawer/add-contact-drawer.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/drawers/add-contact-drawer/add-contact-drawer.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/drawers/add-contact-drawer/add-contact-drawer.tsx',
      category: 'Application',
      subcategory: 'Files',
      chunks: [],
    },
    'files-list-card': {
      name: 'files-list-card',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/drawers/add-contact-drawer/add-contact-drawer.tsx',
        '../blocks/drawers/add-contact-drawer/add-contact-drawer.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/drawers/add-contact-drawer/add-contact-drawer.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/drawers/add-contact-drawer/add-contact-drawer.tsx',
      category: 'Application',
      subcategory: 'Files',
      chunks: [],
    },
    'metric-card-simple': {
      name: 'metric-card-simple',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/kpi-cards/metric-card-simple/metric-card-simple.tsx',
        '../blocks/kpi-cards/metric-card-simple/metric-card-simple.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/kpi-cards/metric-card-simple/metric-card-simple.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/kpi-cards/metric-card-simple/metric-card-simple.tsx',
      category: 'Application',
      subcategory: 'KPI Cards',
      chunks: [],
    },
    'metric-card-with-button': {
      name: 'metric-card-with-button',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/kpi-cards/metric-card-with-button/metric-card-with-button.tsx',
        '../blocks/kpi-cards/metric-card-with-button/metric-card-with-button.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/kpi-cards/metric-card-with-button/metric-card-with-button.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/kpi-cards/metric-card-with-button/metric-card-with-button.tsx',
      category: 'Application',
      subcategory: 'KPI Cards',
      chunks: [],
    },
    'metric-card-with-icon': {
      name: 'metric-card-with-icon',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/kpi-cards/metric-card-with-icon/metric-card-with-icon.tsx',
        '../blocks/kpi-cards/metric-card-with-icon/metric-card-with-icon.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/kpi-cards/metric-card-with-icon/metric-card-with-icon.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/kpi-cards/metric-card-with-icon/metric-card-with-icon.tsx',
      category: 'Application',
      subcategory: 'KPI Cards',
      chunks: [],
    },
    'sortable-task-list': {
      name: 'sortable-task-list',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/lists/sortable-task-list/sortable-task-list.tsx',
        '../blocks/lists/sortable-task-list/sortable-task-list.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/lists/sortable-task-list/sortable-task-list.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/lists/sortable-task-list/sortable-task-list.tsx',
      category: 'Application',
      subcategory: 'Lists',
      chunks: [],
    },
    'organization-menu': {
      name: 'organization-menu',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/menus/organization-menu/organization-menu.tsx',
        '../blocks/menus/organization-menu/organization-menu.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/menus/organization-menu/organization-menu.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/menus/organization-menu/organization-menu.tsx',
      category: 'Application',
      subcategory: 'Menus',
      chunks: [],
    },
    'roles-menu': {
      name: 'roles-menu',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/menus/roles-menu/roles-menu.tsx',
        '../blocks/menus/roles-menu/roles-menu.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import('@/registry/default/blocks/menus/roles-menu/roles-menu.tsx'),
      ),
      source: '__registry__/default/blocks/menus/roles-menu/roles-menu.tsx',
      category: 'Application',
      subcategory: 'Menus',
      chunks: [],
    },
    'user-menu': {
      name: 'user-menu',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/menus/user-menu/user-menu.tsx',
        '../blocks/menus/user-menu/user-menu.stories.tsx',
      ],
      component: React.lazy(
        () => import('@/registry/default/blocks/menus/user-menu/user-menu.tsx'),
      ),
      source: '__registry__/default/blocks/menus/user-menu/user-menu.tsx',
      category: 'Application',
      subcategory: 'Menus',
      chunks: [],
    },
    'feedback-modal': {
      name: 'feedback-modal',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/modals/feedback-modal/feedback-modal.tsx',
        '../blocks/modals/feedback-modal/feedback-modal.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/modals/feedback-modal/feedback-modal.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/modals/feedback-modal/feedback-modal.tsx',
      category: 'Application',
      subcategory: 'Modals',
      chunks: [],
    },
    'invite-people-modal': {
      name: 'invite-people-modal',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/modals/invite-people-modal/invite-people-modal.tsx',
        '../blocks/modals/invite-people-modal/invite-people-modal.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/modals/invite-people-modal/invite-people-modal.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/modals/invite-people-modal/invite-people-modal.tsx',
      category: 'Application',
      subcategory: 'Modals',
      chunks: [],
    },
    'manage-tags-modal': {
      name: 'manage-tags-modal',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/modals/manage-tags-modal/manage-tags-modal.tsx',
        '../blocks/modals/manage-tags-modal/manage-tags-modal.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/modals/manage-tags-modal/manage-tags-modal.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/modals/manage-tags-modal/manage-tags-modal.tsx',
      category: 'Application',
      subcategory: 'Modals',
      chunks: [],
    },
    'select-users-modal': {
      name: 'select-users-modal',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/modals/select-users-modal/select-users-modal.tsx',
        '../blocks/modals/select-users-modal/user-persona.tsx',
        '../blocks/modals/select-users-modal/select-users-modal.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/modals/select-users-modal/select-users-modal.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/modals/select-users-modal/select-users-modal.tsx',
      category: 'Application',
      subcategory: 'Modals',
      chunks: [],
    },
    'integration-card': {
      name: 'integration-card',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/settings/integration-card/integration-card.tsx',
        '../blocks/settings/integration-card/integration-card.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/settings/integration-card/integration-card.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/settings/integration-card/integration-card.tsx',
      category: 'Application',
      subcategory: 'Settings',
      chunks: [],
    },
    'notification-settings': {
      name: 'notification-settings',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/settings/notification-settings/notification-settings.tsx',
        '../blocks/settings/notification-settings/notification-settings.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/settings/notification-settings/notification-settings.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/settings/notification-settings/notification-settings.tsx',
      category: 'Application',
      subcategory: 'Settings',
      chunks: [],
    },
    'workspace-members-settings': {
      name: 'workspace-members-settings',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/settings/workspace-members-settings/workspace-members-settings.tsx',
        '../blocks/settings/workspace-members-settings/workspace-members-settings.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/settings/workspace-members-settings/workspace-members-settings.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/settings/workspace-members-settings/workspace-members-settings.tsx',
      category: 'Application',
      subcategory: 'Settings',
      chunks: [],
    },
    'double-sidebar': {
      name: 'double-sidebar',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/settings/workspace-members-settings/workspace-members-settings.tsx',
        '../blocks/settings/workspace-members-settings/workspace-members-settings.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/settings/workspace-members-settings/workspace-members-settings.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/settings/workspace-members-settings/workspace-members-settings.tsx',
      category: 'Application',
      subcategory: 'Layouts',
      chunks: [],
    },
    'recessed-sidebar': {
      name: 'recessed-sidebar',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/sidebar-layouts/recessed-sidebar/recessed-sidebar.tsx',
        '../blocks/sidebar-layouts/recessed-sidebar/recessed-sidebar.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/sidebar-layouts/recessed-sidebar/recessed-sidebar.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/sidebar-layouts/recessed-sidebar/recessed-sidebar.tsx',
      category: 'Application',
      subcategory: 'Layouts',
      chunks: [],
    },
    'recessed-sidebar-contrast': {
      name: 'recessed-sidebar-contrast',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/sidebar-layouts/recessed-sidebar-contrast/recessed-sidebar-contrast.tsx',
        '../blocks/sidebar-layouts/recessed-sidebar-contrast/recessed-sidebar-contrast.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/sidebar-layouts/recessed-sidebar-contrast/recessed-sidebar-contrast.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/sidebar-layouts/recessed-sidebar-contrast/recessed-sidebar-contrast.tsx',
      category: 'Application',
      subcategory: 'Layouts',
      chunks: [],
    },
    'sidebar-with-navbar': {
      name: 'sidebar-with-navbar',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/sidebar-layouts/sidebar-with-navbar/sidebar-with-navbar.tsx',
        '../blocks/sidebar-layouts/sidebar-with-navbar/sidebar-with-navbar.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/sidebar-layouts/sidebar-with-navbar/sidebar-with-navbar.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/sidebar-layouts/sidebar-with-navbar/sidebar-with-navbar.tsx',
      category: 'Application',
      subcategory: 'Layouts',
      chunks: [],
    },
    'sortable-nav-group-items': {
      name: 'sortable-nav-group-items',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/sidebar-layouts/sortable-nav-group/sortable-nav-group.tsx',
        '../blocks/sidebar-layouts/sortable-nav-group/sortable-nav-group.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/sidebar-layouts/sortable-nav-group/sortable-nav-group.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/sidebar-layouts/sortable-nav-group/sortable-nav-group.tsx',
      category: 'Application',
      subcategory: 'Layouts',
      chunks: [],
    },
    'navbar-branded': {
      name: 'navbar-branded',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/stacked-layouts/navbar-branded/navbar-branded.tsx',
        '../blocks/stacked-layouts/navbar-branded/navbar-branded.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/stacked-layouts/navbar-branded/navbar-branded.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/stacked-layouts/navbar-branded/navbar-branded.tsx',
      category: 'Application',
      subcategory: 'Layouts',
      chunks: [],
    },
    'navbar-tabs': {
      name: 'navbar-tabs',
      type: 'registry:block',
      registryDependencies: undefined,
      files: [
        '../blocks/stacked-layouts/navbar-tabs/navbar-tabs.tsx',
        '../blocks/stacked-layouts/navbar-tabs/navbar-tabs.stories.tsx',
      ],
      component: React.lazy(
        () =>
          import(
            '@/registry/default/blocks/stacked-layouts/navbar-tabs/navbar-tabs.tsx'
          ),
      ),
      source:
        '__registry__/default/blocks/stacked-layouts/navbar-tabs/navbar-tabs.tsx',
      category: 'Application',
      subcategory: 'Layouts',
      chunks: [],
    },
  },
}
